// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6QUFDYSOeig-Vs2WpJKJevUAJ14fH9A',
    appId: '1:694735610840:web:7f0d4893b848d2fc5108ad',
    messagingSenderId: '694735610840',
    projectId: 'vartameet-5b58b',
    authDomain: 'vartameet-5b58b.firebaseapp.com',
    storageBucket: 'vartameet-5b58b.appspot.com',
    measurementId: 'G-CDH9B8NVDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsckRgWibeWwrz5z8Twzvt4OgF3usjHvw',
    appId: '1:694735610840:android:8492344cff45307b5108ad',
    messagingSenderId: '694735610840',
    projectId: 'vartameet-5b58b',
    storageBucket: 'vartameet-5b58b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZpI-HMHRyZ6Y4UzshDAMUo5tJGSI448',
    appId: '1:694735610840:ios:eab6fba0c2c443a55108ad',
    messagingSenderId: '694735610840',
    projectId: 'vartameet-5b58b',
    storageBucket: 'vartameet-5b58b.appspot.com',
    iosBundleId: 'com.example.vartameetComputer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZpI-HMHRyZ6Y4UzshDAMUo5tJGSI448',
    appId: '1:694735610840:ios:dcba93a83921f92c5108ad',
    messagingSenderId: '694735610840',
    projectId: 'vartameet-5b58b',
    storageBucket: 'vartameet-5b58b.appspot.com',
    iosBundleId: 'com.example.vartameetComputer.RunnerTests',
  );
}
